Close

diff --git a/deployments/google/init b/deployments/google/init
--- a/deployments/google/init
+++ b/deployments/google/init
@@ -2,14 +2,41 @@
 
 set -euo pipefail
 
+ROOT_DIR=$(pwd)
 PROJECT_ID=""
 NO_DELETION_PROTECTION=false
+DESTROY=false
+AUTO_APPROVE=false
+KUBERNETES_TRANSIT_TOKEN=""
+TRANSIT_KEY1="N/A (Skipped)"
+TRANSIT_KEY2="N/A (Skipped)"
+TRANSIT_KEY3="N/A (Skipped)"
+TRANSIT_KEY4="N/A (Skipped)"
+TRANSIT_KEY5="N/A (Skipped)"
+TRANSIT_ROOT_TOKEN="N/A (Skipped)"
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
     --no-deletion-protection)
       NO_DELETION_PROTECTION=true
       shift
+      ;;
+    --destroy)
+      DESTROY=true
+      shift
+      ;;
+    -y|--auto-approve)
+      AUTO_APPROVE=true
+      shift
+      ;;
+    --kubernetes-transit-token)
+      if [[ -n "${2:-}" ]]; then
+        KUBERNETES_TRANSIT_TOKEN="$2"
+        shift 2
+      else
+        echo "Error: --kubernetes-bootstrap-token requires a value."
+        exit 1
+      fi
       ;;
     -*)
       echo "Error: Unknown flag '$1'"
@@ -41,42 +68,70 @@ if [[ "$NO_DELETION_PROTECTION" == true ]]; then
   TOFU_ARGS+=("--no-deletion-protection")
 fi
 
+if [[ "$DESTROY" == true ]]; then
+  TOFU_ARGS+=("--destroy")
+fi
+
+if [[ "$AUTO_APPROVE" == true ]]; then
+  TOFU_ARGS+=("--auto-approve")
+fi
+
 echo "=== Initialising Google Cloud Infrastructure ==="
 ./deployments/google/init-tofu "${TOFU_ARGS[@]}"
+if [[ "$DESTROY" == true ]]; then
+  exit 1
+fi
 
 echo " "
 echo "=== Initialising the transit secrets manager ==="
-TRANSIT_OUTPUT=$(./deployments/google/init-transit)
+if [[ -z "$KUBERNETES_TRANSIT_TOKEN" ]]; then
+  TRANSIT_OUTPUT=$(./deployments/google/init-transit | tee /dev/stderr)
 
-TRANSIT_KEY1=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 1:" | awk '{print $NF}')
-TRANSIT_KEY2=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 2:" | awk '{print $NF}')
-TRANSIT_KEY3=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 3:" | awk '{print $NF}')
-TRANSIT_KEY4=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 4:" | awk '{print $NF}')
-TRANSIT_KEY5=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 5:" | awk '{print $NF}')
-TRANSIT_ROOT_TOKEN=$(echo "$TRANSIT_OUTPUT" | grep "Initial Root Token:" | awk '{print $NF}')
-KUBERNETES_BOOTSTRAP_TOKEN=$(echo "$TRANSIT_OUTPUT" | grep "Kubernetes Bootstrap Token:" | awk '{print $NF}')
+  echo "Extracting keys and tokens..."
+  TRANSIT_KEY1=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 1:" | awk '{print $NF}')
+  TRANSIT_KEY2=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 2:" | awk '{print $NF}')
+  TRANSIT_KEY3=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 3:" | awk '{print $NF}')
+  TRANSIT_KEY4=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 4:" | awk '{print $NF}')
+  TRANSIT_KEY5=$(echo "$TRANSIT_OUTPUT" | grep "Unseal Key 5:" | awk '{print $NF}')
+  TRANSIT_ROOT_TOKEN=$(echo "$TRANSIT_OUTPUT" | grep "Initial Root Token:" | awk '{print $NF}')
+  KUBERNETES_TRANSIT_TOKEN=$(echo "$TRANSIT_OUTPUT" | grep "Kubernetes Transit Token:" | awk '{print $NF}')
 
-echo "Important keys and tokens (will be printed later again):"
-echo "Transit Unseal Key 1: $TRANSIT_KEY1"
-echo "Transit Unseal Key 2: $TRANSIT_KEY2"
-echo "Transit Unseal Key 3: $TRANSIT_KEY3"
-echo "Transit Unseal Key 4: $TRANSIT_KEY4"
-echo "Transit Unseal Key 5: $TRANSIT_KEY5"
-echo "Transit Root Token: $TRANSIT_ROOT_TOKEN"
-echo "Kubernetes Transit Token: $KUBERNETES_BOOTSTRAP_TOKEN"
+  echo "Important keys and tokens (will be printed later again):"
+  echo "Unseal Key 1: $TRANSIT_KEY1"
+  echo "Unseal Key 2: $TRANSIT_KEY2"
+  echo "Unseal Key 3: $TRANSIT_KEY3"
+  echo "Unseal Key 4: $TRANSIT_KEY4"
+  echo "Unseal Key 5: $TRANSIT_KEY5"
+  echo "Root Token: $TRANSIT_ROOT_TOKEN"
+  echo "Kubernetes Transit Token: $KUBERNETES_TRANSIT_TOKEN"
+else
+  echo "Skipping transit secrets manager initialization because the Kubernetes transit token was provided"
+fi
+
+echo " "
+echo "=== Connecting kubectl to the live cluster ==="
+echo "Getting connection details..."
+cd ./deployments/google/tofu/
+CLUSTER_NAME=$(terraform output -raw psp_cluster_name)
+CLUSTER_ZONE=$(terraform output -raw psp_cluster_zone)
+cd "$ROOT_DIR"
+echo "Cluster name: $CLUSTER_NAME"
+echo "Cluster zone: $CLUSTER_ZONE"
+echo "Connecting..."
+gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$CLUSTER_ZONE" --project "$PROJECT_ID"
 
 echo " "
 echo "=== Prepare for the main secrets manager in the cluster ==="
-./deployments/google/init-secrets-manager-prepare "$KUBERNETES_BOOTSTRAP_TOKEN"
+./deployments/google/init-secrets-manager-prepare "$KUBERNETES_TRANSIT_TOKEN"
 
 echo " "
-echo "=== Initialise FluxCD"
+echo "=== Initialise FluxCD ==="
 flux install
 ./scripts/update prod
 
 echo " "
 echo "=== Initialise main secrets manager ==="
-SECRETS_OUTPUT=$(./deployments/google/init-secrets-manager)
+SECRETS_OUTPUT=$(./deployments/google/init-secrets-manager | tee /dev/stderr)
 
 SECRETS_KEY1=$(echo "$SECRETS_OUTPUT" | grep "Recovery Key 1:" | awk '{print $NF}')
 SECRETS_KEY2=$(echo "$SECRETS_OUTPUT" | grep "Recovery Key 2:" | awk '{print $NF}')
