Fix CI, add bootstrap layer and add encryption to tofu runners (#132)
* Fix CI and add NP to secrets-manager

* Add tofu controller pod label

* Add the podLabel to the runner, rather than the controller pod

* Add label the right place (hopefully)

* Fix label

* Switch the gateway to the gateway namespace

* Reconcile strategy

* Move the keycloak namespace to foundation

* Add the bootstrap layer

* Update reconcile script

* Disable np in secretns-manager

* Remove default-deny on auth-manager

* Remove default deny on auth manager

* Use the default-deny branch

* Switch to main branch

* Remove default deny

* Use main secrest manager

* Secrets branch

* Use the main branch of the secrets-manager

* Switch to the main branch of the gateway

* Encrypt auth-manager tofu-runner

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -33,7 +33,14 @@ jobs:
     name: Required checks
     runs-on: ubuntu-latest
     needs: [validate]
+    if: always()
     timeout-minutes: 2
     steps:
+      - name: Check dependency status
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "Failing: One or more upstream jobs failed, were cancelled, or skipped."
+          exit 1
+
       - name: Mark as successful
         run: echo "All required jobs have passed!"
